# Generated by Django 3.2 on 2021-04-29 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to=users.models.customer_image_file_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
