# Generated by Django 3.2 on 2021-04-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='intro',
            field=models.TextField(null=True),
        ),
    ]
