# Generated by Django 3.2 on 2021-05-02 08:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210429_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='intro',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
