# Generated by Django 3.2 on 2021-05-02 08:05

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media_cdn/default.jpg', upload_to=users.models.customer_image_file_path),
        ),
    ]
