# Generated by Django 3.2 on 2021-05-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_intouch'),
    ]

    operations = [
        migrations.AddField(
            model_name='intouch',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
