# Generated by Django 3.2 on 2021-05-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210503_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
