# Generated by Django 3.2 on 2021-05-12 11:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210511_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
